#!/bin/sh

#  scribble.rule.sh
#  ThinkerDraw
#
#  Created by 熊 春雷 on 2019/9/9.
#  Copyright © 2019 pandaxcl. All rights reserved.

echo "DERIVED_SOURCES_DIR: $DERIVED_SOURCES_DIR"
echo "$INPUT_FILE_DIR/$INPUT_FILE_NAME"
echo "DEPENDENCIES_GIT: $DEPENDENCIES_GIT"
echo "PROJECT_DIR: $PROJECT_DIR"
echo "RACKET_CMD: $RACKET_CMD --lib ${DEPENDENCIES_GIT}/rule"

export SCRIBBLE_OUTPUT=HPP; $RACKET_CMD "$INPUT_FILE_DIR/$INPUT_FILE_NAME" > "$DERIVED_SOURCES_DIR/$INPUT_FILE_NAME.hpp"
export SCRIBBLE_OUTPUT=CPP; $RACKET_CMD "$INPUT_FILE_DIR/$INPUT_FILE_NAME" > "$DERIVED_SOURCES_DIR/$INPUT_FILE_NAME.cpp.cpp"
export SCRIBBLE_OUTPUT=MM;  $RACKET_CMD "$INPUT_FILE_DIR/$INPUT_FILE_NAME" > "$DERIVED_SOURCES_DIR/$INPUT_FILE_NAME.mm.mm"

# *.scribble
# source "${DEPENDENCIES_GIT}/rule/scribble.rule.sh"

# $(DERIVED_SOURCES_DIR)/$(INPUT_FILE_NAME).hpp
# $(DERIVED_SOURCES_DIR)/$(INPUT_FILE_NAME).cpp.cpp
# $(DERIVED_SOURCES_DIR)/$(INPUT_FILE_NAME).mm.mm
