pushd catch2.git && git pull && popd
pushd clips_core_6_40.git && git pull && popd
pushd clips_uml.git && git pull && popd
pushd cppcoro.git && git pull && popd
pushd cpplinq.git && git pull && popd
pushd cppzmq.git && git pull && popd
pushd cucumber-cpp.git && git pull && popd
pushd fmt.git && git pull && popd
pushd graphviz.git && git pull && popd
pushd grpc.git && git pull && popd
pushd libzmq.git && git pull && popd
pushd mstch.git && git pull && popd
pushd nlohmann-json.git && git pull && popd
pushd rpclib.git && git pull && popd
pushd rttr.git && git pull && popd
pushd rxcpp.git && git pull && popd
pushd yoga.git && git pull && popd
